-- Mockup + proof approval (Order)
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "proofRequired" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "proofStatus" TEXT NOT NULL DEFAULT 'NOT_SENT';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "proofSentAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "proofApprovedAt" TIMESTAMP(3);
