"use strict";

module.exports = Object.freeze({
  CUSTOMER_MEMORY: "CUSTOMER_MEMORY",
  ORDER_MEMORY: "ORDER_MEMORY",
  PAYMENT_MEMORY: "PAYMENT_MEMORY",
  EMAIL_MEMORY: "EMAIL_MEMORY",
  PRODUCTION_MEMORY: "PRODUCTION_MEMORY",
  APPROVAL_MEMORY: "APPROVAL_MEMORY",
  ERROR_MEMORY: "ERROR_MEMORY",
  OPERATOR_MEMORY: "OPERATOR_MEMORY",
});
