/**
 * PO payloads for email / JSON / future PDF — does not send mail.
 */

function preparePOEmail(po) {
  const p = po && typeof po === "object" ? po : {};
  const lines = Array.isArray(p.items) ? p.items : [];
  const body = [
    `Purchase order ${p.poNumber || "DRAFT"}`,
    `Supplier: ${p.supplier || ""}`,
    ``,
    ...lines.map((it) => `- ${it.sku || it.product} ${it.color || ""} ${it.size || ""} × ${it.qty || 0}`),
    ``,
    `Total units: ${p.totalUnits || 0}`,
    p.linkedJobs && p.linkedJobs.length ? `Jobs: ${p.linkedJobs.join(", ")}` : "",
    ``,
    `— Generated by Cheeky OS (not sent automatically)`,
  ]
    .filter(Boolean)
    .join("\n");

  return {
    subject: `PO ${p.poNumber || ""} — ${p.supplier || "supplier"}`.trim(),
    body,
    attachments: [],
    printable: {
      poNumber: p.poNumber,
      supplier: p.supplier,
      items: lines,
      totalUnits: p.totalUnits,
      linkedJobs: p.linkedJobs || [],
    },
  };
}

function preparePOPdfStructure(po) {
  const doc = preparePOEmail(po);
  return {
    title: doc.subject,
    sections: [
      { type: "header", text: doc.printable && doc.printable.supplier },
      { type: "lines", rows: (po && po.items) || [] },
      { type: "footer", text: `Total: ${(po && po.totalUnits) || 0} units` },
    ],
  };
}

module.exports = {
  preparePOEmail,
  preparePOPdfStructure,
};
