"use strict";

module.exports = Object.freeze({
  OPERATOR_COMMAND_RECEIVED: "OPERATOR_COMMAND_RECEIVED",
  OPERATOR_TOOL_EXECUTED: "OPERATOR_TOOL_EXECUTED",
  EMAIL_SEARCH_REQUESTED: "EMAIL_SEARCH_REQUESTED",
  EMAIL_SEARCH_COMPLETED: "EMAIL_SEARCH_COMPLETED",
  CUSTOMER_CONTEXT_REQUESTED: "CUSTOMER_CONTEXT_REQUESTED",
  CUSTOMER_CONTEXT_BUILT: "CUSTOMER_CONTEXT_BUILT",
  PAYMENT_EVENT_RECEIVED: "PAYMENT_EVENT_RECEIVED",
  DEPOSIT_VERIFIED: "DEPOSIT_VERIFIED",
  PRODUCTION_GATE_CHECKED: "PRODUCTION_GATE_CHECKED",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_GRANTED: "APPROVAL_GRANTED",
  APPROVAL_DENIED: "APPROVAL_DENIED",
  ERROR_RECORDED: "ERROR_RECORDED",
});
