ALTER TABLE "CaptureOrder" ADD COLUMN "paymentStatus" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CaptureOrder" ADD COLUMN "depositRequired" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "CaptureOrder" ADD COLUMN "depositReceived" BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE "CaptureOrder" ADD COLUMN "balanceDue" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CaptureOrder" ADD COLUMN "paymentNotes" TEXT NOT NULL DEFAULT '';
