import type { Job, Order } from "@prisma/client";
import {
  isMailTransportConfigured,
  sendEmail,
} from "../lib/mailClient";
import { db } from "../db/client";
import { OrderNotFoundError } from "./orderEvaluator";
import { assertActionAllowed } from "./safetyGuard.service";
import { syncOrderToSharePoint } from "./sharepointOrderSync";
import { logger } from "../utils/logger";
import { logExceptionReviewSafe } from "./exceptionReviewService";

const VENDOR_NAME = "Peter";
const ACTIVE_REQUEST_STATUSES = ["DRAFT", "SENT", "RECEIVED"] as const;

export function isDigitizingEnabled(): boolean {
  return (
    String(process.env.DIGITIZING_ENABLED ?? "")
      .trim()
      .toLowerCase() === "true"
  );
}

function getDigitizerEmail(): string {
  return String(process.env.DIGITIZER_EMAIL ?? "").trim();
}

function normalizePrintMethod(raw: string | null | undefined): string {
  return String(raw ?? "").trim().toUpperCase();
}

function notesLower(notes: string): string {
  return String(notes ?? "").toLowerCase();
}

/** Keywords in notes that imply digitizing work. */
const DIGITIZE_NOTE_KEYWORDS = [
  "digitize",
  "embroidery",
  "embroidered",
  "left chest logo",
];

export function isDigitizingRequiredForOrder(order: Order): boolean {
  if (order.digitizingRequired === true) return true;
  const pm = normalizePrintMethod(order.printMethod);
  if (pm === "EMB" || pm.includes("EMBROID")) return true;
  const n = notesLower(order.notes);
  for (const kw of DIGITIZE_NOTE_KEYWORDS) {
    if (n.includes(kw)) return true;
  }
  return false;
}

function inferPlacementFromNotes(notes: string): string {
  const n = notesLower(notes);
  if (n.includes("left chest")) return "Left chest (from notes)";
  if (n.includes("right chest")) return "Right chest (from notes)";
  if (n.includes("full back") || n.includes("full-back")) return "Full back (from notes)";
  if (n.includes("center chest")) return "Center chest (from notes)";
  return "Not specified";
}

function buildDigitizingEmail(order: Order, job: Job | null): {
  subject: string;
  body: string;
} {
  const subject = `Digitizing Request - Order ${order.id} - ${order.customerName}`;
  const placement = inferPlacementFromNotes(order.notes);
  const jobLine = job ? job.id : "Not created yet";

  const body = [
    `Digitizing request for Cheeky OS (vendor: ${VENDOR_NAME})`,
    "",
    `Customer Name: ${order.customerName}`,
    `Order ID: ${order.id}`,
    `Job ID: ${jobLine}`,
    `Garment Type: ${order.garmentType ?? "—"}`,
    `Quantity: ${order.quantity ?? "—"}`,
    `Print Method: ${order.printMethod ?? "—"}`,
    `Requested Placement: ${placement}`,
    "",
    "Notes:",
    order.notes || "(none)",
    "",
    "Requested turnaround: Standard",
    "",
    "Artwork files to follow / attach manually if needed",
    "",
    "(Outbound only — no artwork URLs or attachments generated by this system.)",
  ].join("\n");

  return { subject, body };
}

export type CreateDigitizingRequestResult =
  | {
      success: true;
      required: false;
      message: "Digitizing not required";
    }
  | {
      success: true;
      required: true;
      idempotent: true;
      digitizingRequestId: string;
      status: string;
      simulated: boolean;
    }
  | {
      success: true;
      required: true;
      simulated: boolean;
      digitizingRequestId: string;
      status: string;
      error?: string;
    };

async function safeSharePoint(orderId: string): Promise<void> {
  try {
    await syncOrderToSharePoint(orderId);
  } catch (spErr) {
    const spMsg = spErr instanceof Error ? spErr.message : String(spErr);
    logger.warn(`digitizingService: SharePoint sync failed for ${orderId}: ${spMsg}`);
  }
}

async function appendJobDigitizingNote(
  job: Job | null,
  record: { id: string; status: string }
): Promise<void> {
  if (!job) return;
  const line = `DigitizingRequest ${record.id}: ${record.status}`;
  const n = (job.notes ?? "").trim();
  if (n.includes(record.id)) return;
  await db.job.update({
    where: { id: job.id },
    data: { notes: n ? `${n}\n${line}` : line },
  });
}

export async function createDigitizingRequestForOrder(
  orderId: string
): Promise<CreateDigitizingRequestResult> {
  const id = String(orderId ?? "").trim();
  if (!id) {
    throw new Error("Missing order id");
  }

  const order = await db.order.findUnique({ where: { id } });
  if (!order) {
    throw new OrderNotFoundError(id);
  }

  const job = await db.job.findUnique({ where: { orderId: id } });

  if (!isDigitizingRequiredForOrder(order)) {
    return {
      success: true,
      required: false,
      message: "Digitizing not required",
    };
  }

  assertActionAllowed(order, "REQUEST_DIGITIZING");

  const existing = await db.digitizingRequest.findFirst({
    where: {
      orderId: id,
      vendorName: VENDOR_NAME,
      status: { in: [...ACTIVE_REQUEST_STATUSES] },
    },
  });

  if (existing) {
    await safeSharePoint(id);
    return {
      success: true,
      required: true,
      idempotent: true,
      digitizingRequestId: existing.id,
      status: existing.status,
      simulated: existing.simulated,
    };
  }

  const { subject, body } = buildDigitizingEmail(order, job);
  const recipientEmail = getDigitizerEmail();
  const digitizingOn = isDigitizingEnabled();
  const now = new Date();

  let record = await db.digitizingRequest.create({
    data: {
      orderId: id,
      jobId: job?.id ?? null,
      vendorName: VENDOR_NAME,
      subject,
      body,
      recipientEmail: recipientEmail || "(not-configured)",
      status: "DRAFT",
    },
  });

  if (!digitizingOn) {
    await db.order.update({
      where: { id },
      data: {
        digitizingRequired: true,
        digitizingStatus: "DRAFT",
        digitizingRequestedAt: null,
      },
    });
    logger.info(
      `digitizingService: simulated DRAFT (DIGITIZING_ENABLED!=true) order=${id} request=${record.id}`
    );
    await appendJobDigitizingNote(job, record);
    await safeSharePoint(id);
    return {
      success: true,
      required: true,
      simulated: true,
      digitizingRequestId: record.id,
      status: "DRAFT",
    };
  }

  if (
    !recipientEmail ||
    !isMailTransportConfigured()
  ) {
    const errDetail = [
      !recipientEmail ? "DIGITIZER_EMAIL is missing" : null,
      !isMailTransportConfigured()
        ? "SMTP is not fully configured (SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM)"
        : null,
    ]
      .filter(Boolean)
      .join("; ");

    record = await db.digitizingRequest.update({
      where: { id: record.id },
      data: {
        status: "FAILED",
        errorMessage: errDetail,
        simulated: false,
      },
    });

    await db.order.update({
      where: { id },
      data: {
        digitizingRequired: true,
        digitizingStatus: "FAILED",
        digitizingRequestedAt: null,
      },
    });

    logger.warn(
      `digitizingService: DIGITIZING_ENABLED but mail not ready — ${errDetail} order=${id}`
    );
    logExceptionReviewSafe({
      orderId: id,
      jobId: job?.id ?? null,
      type: "DIGITIZING_CONFIG_FAILED",
      source: "DIGITIZING",
      severity: "HIGH",
      message: errDetail,
      detailsJson: JSON.stringify({ digitizingRequestId: record.id }),
    });
    await appendJobDigitizingNote(job, record);
    await safeSharePoint(id);

    return {
      success: true,
      required: true,
      simulated: false,
      digitizingRequestId: record.id,
      status: "FAILED",
      error: errDetail,
    };
  }

  const sendResult = await sendEmail({
    to: recipientEmail,
    subject,
    text: body,
  });

  if (sendResult.success === true) {
    record = await db.digitizingRequest.update({
      where: { id: record.id },
      data: {
        status: "SENT",
        sentAt: now,
        simulated: false,
        recipientEmail,
        errorMessage: null,
      },
    });

    await db.order.update({
      where: { id },
      data: {
        digitizingRequired: true,
        digitizingStatus: "SENT",
        digitizingRequestedAt: now,
      },
    });

    logger.info(
      `digitizingService: digitizing email sent order=${id} request=${record.id} to=${recipientEmail}`
    );
  } else if (sendResult.success === false) {
    record = await db.digitizingRequest.update({
      where: { id: record.id },
      data: {
        status: "FAILED",
        errorMessage: sendResult.error,
        simulated: false,
        recipientEmail,
      },
    });

    await db.order.update({
      where: { id },
      data: {
        digitizingRequired: true,
        digitizingStatus: "FAILED",
        digitizingRequestedAt: null,
      },
    });

    logger.warn(
      `digitizingService: email send failed order=${id} request=${record.id}: ${sendResult.error}`
    );
    logExceptionReviewSafe({
      orderId: id,
      jobId: job?.id ?? null,
      type: "DIGITIZING_SEND_FAILED",
      source: "DIGITIZING",
      severity: "HIGH",
      message: sendResult.error,
      detailsJson: JSON.stringify({ digitizingRequestId: record.id }),
    });
  }

  await appendJobDigitizingNote(job, record);
  await safeSharePoint(id);

  return {
    success: true,
    required: true,
    simulated: false,
    digitizingRequestId: record.id,
    status: record.status,
    ...(record.status === "FAILED" && record.errorMessage
      ? { error: record.errorMessage }
      : {}),
  };
}
